#define janvier 1
#define fevrier 2
#define mars 3
#define avril 4
#define mai 5
#define juin 6
#define juillet 7
#define aout 8
#define septembre 9
#define octobre 10
#define novembre  11
#define decembre 12
